/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    properties: Property;
    'feed-sources': FeedSource;
    'import-runs': ImportRun;
    'import-issues': ImportIssue;
    leads: Lead;
    'lead-deliveries': LeadDelivery;
    media: Media;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    'feed-sources': FeedSourcesSelect<false> | FeedSourcesSelect<true>;
    'import-runs': ImportRunsSelect<false> | ImportRunsSelect<true>;
    'import-issues': ImportIssuesSelect<false> | ImportIssuesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'lead-deliveries': LeadDeliveriesSelect<false> | LeadDeliveriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      dispatchDueFeeds: TaskDispatchDueFeeds;
      importFeed: TaskImportFeed;
      jobsJanitor: TaskJobsJanitor;
      leadRetentionCleanup: TaskLeadRetentionCleanup;
      catalogLifecycle: TaskCatalogLifecycle;
      recoverLeadDeliveries: TaskRecoverLeadDeliveries;
      deliverLead: TaskDeliverLead;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('owner' | 'admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  slug: string;
  title: string;
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  /**
   * Required for origin=feed; empty for manual properties.
   */
  feedSource?: (number | null) | FeedSource;
  /**
   * Required for origin=feed; paired with feedSource by SQL guard.
   */
  externalId?: string | null;
  origin: 'feed' | 'manual';
  importHash?: string | null;
  firstSeenAt?: string | null;
  lastSeenAt?: string | null;
  lastImportRun?: (number | null) | ImportRun;
  externalComplexId?: string | null;
  externalComplexName?: string | null;
  externalBuildingId?: string | null;
  externalLayoutId?: string | null;
  status: 'active' | 'archived';
  deactivatedAt?: string | null;
  deactivatedByRun?: (number | null) | ImportRun;
  needsReview?: boolean | null;
  publishedAt?: string | null;
  /**
   * Set after lifecycle retention purges object content.
   */
  contentPurgedAt?: string | null;
  /**
   * Public immutable page identity. Feed imports must not rotate it after first publish.
   */
  slug: string;
  market: 'secondary' | 'newbuild';
  category: 'apartment' | 'house' | 'land' | 'commercial';
  dealType: 'sale' | 'rent';
  priceMinor?: number | null;
  currency?: 'RUB' | null;
  pricePerMeterMinor?: number | null;
  rooms?: number | null;
  totalArea?: number | null;
  livingArea?: number | null;
  kitchenArea?: number | null;
  floor?: number | null;
  floors?: number | null;
  region?: string | null;
  locality?: string | null;
  district?: string | null;
  street?: string | null;
  house?: string | null;
  publicAddress?: string | null;
  lat?: number | null;
  lng?: number | null;
  title: string;
  description?: string | null;
  images?:
    | {
        kind: 'external' | 'managed';
        url?: string | null;
        media?: (number | null) | Media;
        alt?: string | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Import-managed fields explicitly owned by manual edits. Slug is not a normal manual override.
   */
  manualOverrides?:
    | {
        field: string;
        setAt: string;
        setBy?: (number | null) | User;
        id?: string | null;
      }[]
    | null;
  unitNumber?: string | null;
  cadastralNumber?: string | null;
  internalComment?: string | null;
  ownerContact?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Owner operations: feed health, schedule, deactivation safety and suspicious-run approval. Store only secret references, never credential URLs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feed-sources".
 */
export interface FeedSource {
  id: number;
  /**
   * Stable source identity used by import jobs and diagnostics.
   */
  code: string;
  title: string;
  parser: 'yrl';
  /**
   * Authoritative market for imported properties from this feed source.
   */
  market: 'secondary' | 'newbuild';
  /**
   * Reference to deployment secret/config value. Do not store credential URLs here.
   */
  feedUrlRef: string;
  enabled?: boolean | null;
  refreshIntervalMinutes: number;
  /**
   * Required when the source is enabled. Create/enable without a value sets now; dispatcher does not skip null rows.
   */
  nextDueAt?: string | null;
  /**
   * Last dispatch attempt time for feed health diagnostics.
   */
  lastAttemptAt?: string | null;
  /**
   * Last successful import completion time.
   */
  lastSuccessfulRunAt?: string | null;
  /**
   * Last import run that was not skipped as unchanged.
   */
  lastFullRunAt?: string | null;
  /**
   * Suspicious-run guard: deactivation above this percent requires explicit owner/admin approval.
   */
  safetyThresholdPercent: number;
  /**
   * Hard safety cap for automatic deactivation during one import run.
   */
  maxDeactivationsPerRun: number;
  lastOfferCount?: number | null;
  lastEtag?: string | null;
  lastModified?: string | null;
  lastFeedHash?: string | null;
  /**
   * Audit-safe approval window for a suspicious import run. Only store run/user/time metadata.
   */
  deactivationApproval?: {
    runId?: (number | null) | ImportRun;
    approvedBy?: (number | null) | User;
    approvedAt?: string | null;
    expiresAt?: string | null;
    consumedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Owner operations: import history, suspicious/interrupted status, heartbeat, safe counters and redacted diagnostics.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs".
 */
export interface ImportRun {
  id: number;
  feedSource: number | FeedSource;
  status: 'queued' | 'running' | 'success' | 'unchanged' | 'suspicious' | 'interrupted' | 'failed';
  queuedAt: string;
  startedAt?: string | null;
  finishedAt?: string | null;
  heartbeatAt?: string | null;
  jobId?: string | null;
  offeredCount?: number | null;
  createdCount?: number | null;
  updatedCount?: number | null;
  archivedCount?: number | null;
  skippedCount?: number | null;
  warningCount?: number | null;
  errorCount?: number | null;
  feedHash?: string | null;
  /**
   * Redacted operational diagnostic only. Do not store feed payload, raw response, PII, credentials or tokens.
   */
  lastErrorRedacted?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Owner operations: import warnings/errors with redacted messages and source links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-issues".
 */
export interface ImportIssue {
  id: number;
  importRun: number | ImportRun;
  feedSource?: (number | null) | FeedSource;
  property?: (number | null) | Property;
  externalId?: string | null;
  severity: 'info' | 'warning' | 'error';
  code: string;
  /**
   * Safe issue text only. No raw XML fragment, PII, credentials, tokens or private feed URL.
   */
  messageRedacted: string;
  field?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Owner operations: agency workflow status and PII retention. External delivery state lives in Lead Deliveries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  /**
   * Optional operator/audit value. Canonical integration and dedup identity is phoneE164.
   */
  phoneRaw?: string | null;
  /**
   * Strictly normalized E.164 phone. Invalid phone must not create a lead.
   */
  phoneE164: string;
  email?: string | null;
  message?: string | null;
  formKind: 'property_request' | 'callback' | 'consultation' | 'generic';
  sourcePage: string;
  referrer?: string | null;
  property?: (number | null) | Property;
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    content?: string | null;
    term?: string | null;
  };
  /**
   * Immutable intake evidence for personal data processing consent.
   */
  consent: {
    accepted: boolean;
    version: string;
    consentedAt: string;
  };
  /**
   * Agency workflow status only. External delivery state lives in lead-deliveries.
   */
  status: 'new' | 'in_progress' | 'processed' | 'rejected';
  idempotencyKey: string;
  retentionMode: 'delete' | 'anonymize';
  /**
   * Optional per-row retention boundary. Project default leadRetentionDays remains canonical unless set.
   */
  retentionUntil?: string | null;
  /**
   * Set when leadRetentionCleanup deleted/anonymized PII for this lead.
   */
  piiPurgedAt?: string | null;
  /**
   * Optional irreversible keyed/HMAC marker. Raw IP/User-Agent are intentionally not stored.
   */
  fraudFingerprint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Owner operations: delivery state, manual retry/recovery and safe diagnostics. CRM channel rows may exist, but CRM adapter execution is deferred until owner enables it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-deliveries".
 */
export interface LeadDelivery {
  id: number;
  lead: number | Lead;
  /**
   * Immutable logical channel ID. Never reuse for another destination.
   */
  channelId: string;
  channelKind: 'messenger' | 'crm';
  /**
   * Delivery state only. Agency workflow status is stored on the lead record.
   */
  status: 'pending' | 'sending' | 'delivered' | 'failed' | 'abandoned';
  attempts: number;
  /**
   * Manual retry: set status to pending, clear active claim/job fields if needed, and set the next safe retry time.
   */
  nextAttemptAt?: string | null;
  /**
   * Payload job identity. Clear only during explicit recovery of an orphaned due delivery.
   */
  jobId?: string | null;
  /**
   * Active claim timestamp. Clear only when recovering a stale sending delivery.
   */
  claimedAt?: string | null;
  /**
   * Worker heartbeat. Stale heartbeat is used by recovery diagnostics.
   */
  heartbeatAt?: string | null;
  deliveredAt?: string | null;
  idempotencyKey: string;
  externalRef?: string | null;
  lastErrorKind?: ('retryable' | 'permanent') | null;
  /**
   * Redacted diagnostic only. No raw payload, PII, response body, token, or secret.
   */
  lastErrorRedacted?: string | null;
  abandonedReason?: ('exhausted' | 'permanent' | 'manual') | null;
  /**
   * Compact safe diagnostics only; raw payload/response, PII and secrets are forbidden.
   */
  attemptLog?:
    | {
        attemptedAt: string;
        safeCode?: string | null;
        outcome: 'delivered' | 'retryable' | 'permanent' | 'skipped';
        redactedNote?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Set when leadRetentionCleanup purges/anonymizes linked delivery diagnostics with the lead.
   */
  diagnosticsPurgedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Old public path. Must be created explicitly by owner action or approved migration.
   */
  from: string;
  to: string;
  statusCode: '301' | '302';
  reason?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'dispatchDueFeeds'
          | 'importFeed'
          | 'jobsJanitor'
          | 'leadRetentionCleanup'
          | 'catalogLifecycle'
          | 'recoverLeadDeliveries'
          | 'deliverLead';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'dispatchDueFeeds'
        | 'importFeed'
        | 'jobsJanitor'
        | 'leadRetentionCleanup'
        | 'catalogLifecycle'
        | 'recoverLeadDeliveries'
        | 'deliverLead'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'feed-sources';
        value: number | FeedSource;
      } | null)
    | ({
        relationTo: 'import-runs';
        value: number | ImportRun;
      } | null)
    | ({
        relationTo: 'import-issues';
        value: number | ImportIssue;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'lead-deliveries';
        value: number | LeadDelivery;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  status?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  feedSource?: T;
  externalId?: T;
  origin?: T;
  importHash?: T;
  firstSeenAt?: T;
  lastSeenAt?: T;
  lastImportRun?: T;
  externalComplexId?: T;
  externalComplexName?: T;
  externalBuildingId?: T;
  externalLayoutId?: T;
  status?: T;
  deactivatedAt?: T;
  deactivatedByRun?: T;
  needsReview?: T;
  publishedAt?: T;
  contentPurgedAt?: T;
  slug?: T;
  market?: T;
  category?: T;
  dealType?: T;
  priceMinor?: T;
  currency?: T;
  pricePerMeterMinor?: T;
  rooms?: T;
  totalArea?: T;
  livingArea?: T;
  kitchenArea?: T;
  floor?: T;
  floors?: T;
  region?: T;
  locality?: T;
  district?: T;
  street?: T;
  house?: T;
  publicAddress?: T;
  lat?: T;
  lng?: T;
  title?: T;
  description?: T;
  images?:
    | T
    | {
        kind?: T;
        url?: T;
        media?: T;
        alt?: T;
        order?: T;
        id?: T;
      };
  manualOverrides?:
    | T
    | {
        field?: T;
        setAt?: T;
        setBy?: T;
        id?: T;
      };
  unitNumber?: T;
  cadastralNumber?: T;
  internalComment?: T;
  ownerContact?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feed-sources_select".
 */
export interface FeedSourcesSelect<T extends boolean = true> {
  code?: T;
  title?: T;
  parser?: T;
  market?: T;
  feedUrlRef?: T;
  enabled?: T;
  refreshIntervalMinutes?: T;
  nextDueAt?: T;
  lastAttemptAt?: T;
  lastSuccessfulRunAt?: T;
  lastFullRunAt?: T;
  safetyThresholdPercent?: T;
  maxDeactivationsPerRun?: T;
  lastOfferCount?: T;
  lastEtag?: T;
  lastModified?: T;
  lastFeedHash?: T;
  deactivationApproval?:
    | T
    | {
        runId?: T;
        approvedBy?: T;
        approvedAt?: T;
        expiresAt?: T;
        consumedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs_select".
 */
export interface ImportRunsSelect<T extends boolean = true> {
  feedSource?: T;
  status?: T;
  queuedAt?: T;
  startedAt?: T;
  finishedAt?: T;
  heartbeatAt?: T;
  jobId?: T;
  offeredCount?: T;
  createdCount?: T;
  updatedCount?: T;
  archivedCount?: T;
  skippedCount?: T;
  warningCount?: T;
  errorCount?: T;
  feedHash?: T;
  lastErrorRedacted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-issues_select".
 */
export interface ImportIssuesSelect<T extends boolean = true> {
  importRun?: T;
  feedSource?: T;
  property?: T;
  externalId?: T;
  severity?: T;
  code?: T;
  messageRedacted?: T;
  field?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phoneRaw?: T;
  phoneE164?: T;
  email?: T;
  message?: T;
  formKind?: T;
  sourcePage?: T;
  referrer?: T;
  property?: T;
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        content?: T;
        term?: T;
      };
  consent?:
    | T
    | {
        accepted?: T;
        version?: T;
        consentedAt?: T;
      };
  status?: T;
  idempotencyKey?: T;
  retentionMode?: T;
  retentionUntil?: T;
  piiPurgedAt?: T;
  fraudFingerprint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-deliveries_select".
 */
export interface LeadDeliveriesSelect<T extends boolean = true> {
  lead?: T;
  channelId?: T;
  channelKind?: T;
  status?: T;
  attempts?: T;
  nextAttemptAt?: T;
  jobId?: T;
  claimedAt?: T;
  heartbeatAt?: T;
  deliveredAt?: T;
  idempotencyKey?: T;
  externalRef?: T;
  lastErrorKind?: T;
  lastErrorRedacted?: T;
  abandonedReason?: T;
  attemptLog?:
    | T
    | {
        attemptedAt?: T;
        safeCode?: T;
        outcome?: T;
        redactedNote?: T;
        id?: T;
      };
  diagnosticsPurgedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  statusCode?: T;
  reason?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDispatchDueFeeds".
 */
export interface TaskDispatchDueFeeds {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskImportFeed".
 */
export interface TaskImportFeed {
  input: {
    feedSourceId: string;
    importRunId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskJobsJanitor".
 */
export interface TaskJobsJanitor {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskLeadRetentionCleanup".
 */
export interface TaskLeadRetentionCleanup {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCatalogLifecycle".
 */
export interface TaskCatalogLifecycle {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRecoverLeadDeliveries".
 */
export interface TaskRecoverLeadDeliveries {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDeliverLead".
 */
export interface TaskDeliverLead {
  input: {
    leadDeliveryId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}